project_id = "bzyohsokcfjlmbguijow"

[functions.generate-signed-url]
verify_jwt = true

[functions.smart-upload]
verify_jwt = true

[functions.generate-preview]
verify_jwt = true

[functions.create-share-link]
verify_jwt = true

[functions.get-shared-file]
verify_jwt = false

[functions.reset-folder-visit]
verify_jwt = true